name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Plan (${{ matrix.environment }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Optional: prevents one env failure from stopping the other
      matrix:
        environment: [dev, prod]

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      TF_CONFIG_DIR: ./
      TF_WORKSPACE: app-infra-123-vm-${{ matrix.environment }}

    defaults:
      run:
        working-directory: ${{ env.TF_CONFIG_DIR }}

    steps:
      - name: Checkout (current repo)
        uses: actions/checkout@v6

      - name: Checkout (blueprint repo)
        uses: actions/checkout@v6
        with:
          repository: benjamin-lykins/infra-aws
          sparse-checkout: blueprints/vm
          path: infra-aws

      - name: Copy VM blueprint into repo root
        run: |
          rsync -a infra-aws/blueprints/vm/ ./

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        # Ensure the 'tfvars' directory actually exists in your repo structure
        run: terraform plan -var-file=tfvars/app-infra-123-vm-${{ matrix.environment }}.tfvars -input=false -out=${{ matrix.environment }}-${{ github.run_id }}.tfplan
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}-${{ github.run_id }}.tfplan
          path: ${{ matrix.environment }}-${{ github.run_id }}.tfplan