name: Terraform Plan + Apply (CLI-driven)

on:
  workflow_dispatch:
    inputs:
      terraform-approve:
        type: boolean
        description: Approve Terraform Apply 
        default: false
      # terraform-plan-artifact:
      #   type: string
      #   description: Terraform Plan artifact name (from previous workflow)
      #   default: ""

jobs:
  terraform-cli-run:
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }} # TFC API token
      TF_CONFIG_DIR: ./                                                   # Path to Terraform files
      TF_WORKSPACE: app-infra-123-vm                                     # Workspace name
    
    defaults:
      run:
        working-directory: ${{ env.TF_CONFIG_DIR }}

    steps:
      - name: Checkout (current repo)
        uses: actions/checkout@v6

      - name: Checkout (blueprint repo)
        uses: actions/checkout@v6
        with:
          repository: benjamin-lykins/infra-aws
          sparse-checkout: blueprints/vm
          path: infra-aws

      - name: Copy VM blueprint into repo root
        run: |
          rsync -a infra-aws/blueprints/vm/ ./

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=tfvars/app-infra-123-dev.tfvars -input=false -out=${{ github.run_id }}.tfplan

      - name: Read file content
        id: get_file_content
        run: |
          FILE_CONTENT=$(cat ${{ github.run_id }}.tfplan)
          echo "content=$FILE_CONTENT" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: benjamin-lykins
          minimum-approvals: 1
          issue-body: |
            "Terraform Plan is ready for review. Please approve to proceed with Terraform Apply."


            ${{ steps.get_file_content.outputs.content }}

      - name: Terraform Apply
        if: ${{ inputs.terraform-approve == true }}
        run: terraform apply -auto-approve -input=false -var-file=tfvars/app-infra-123-dev.tfvars ${{ github.run_id }}.tfplan